global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alert_manager:9093"

scrape_configs:

  - job_name: "target_cadvisor"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["container_cadvisor:8080"]
        labels:
          application: "container-contain"

  - job_name: "target_flaskapp"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["container_flaskapp:5000"]
        labels:
          application: "app-python"
